CALL CUSTOMERS.PUBLIC.ITERATE_SOURCEFILELIST_CONFIG('CUSTOMERS','PUBLIC');
CALL CUSTOMERS.PUBLIC.CREATE_TABLES(
'CUSTOMERS',//config database name
'PUBLIC'//config schema name
);

CALL CUSTOMERS.PUBLIC.RAW_DATA_INGESTION(
'CUSTOMERS',//config database name
'PUBLIC'//config schema name
);
